/**
 * ============================================================
 * ARCHIVO: claves_examen.js
 * UBICACIÓN: /backend/claves_examen.js (Al lado de server.js)
 * PROPÓSITO: Bóveda de respuestas correctas para todas las áreas.
 * ============================================================
 */

const clavesSociales = {
    "0": {respuesta: "D", materia: "Habilidad del Razonamiento Verbal"},
    "1": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal"},
    "2": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal"},
    "3": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal"},
    "4": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal"},
    "5": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal"}, 
    "6": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal"},
    "7": {respuesta: "D", materia: "Habilidad del Razonamiento Verbal"},
    "8": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal"},
    "9": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal"},
    "10": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal"},
    "11": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal"},
    "12": {respuesta: "D", materia: "Español" },
    "13": {respuesta: "B", materia: "Español" },
    "14": {respuesta: "D", materia: "Español"},
    "15": {respuesta: "A", materia: "Español"},
    "16": {respuesta: "C", materia: "Español"},
    "17": {respuesta: "A", materia: "Español"},
    "18": {respuesta: "B", materia: "Español"}, 
    "19": {respuesta: "C", materia: "Español"},
    "20": {respuesta: "C", materia: "Español"},
    "21": {respuesta: "A", materia: "Español"},
    "22": {respuesta: "D", materia: "Español"},
    "23": {respuesta: "B", materia: "Español"}, 
    "24": {respuesta: "D", materia: "Historia"}, 
    "25": {respuesta: "C", materia: "Historia"},
    "26": {respuesta: "B", materia: "Historia"},
    "27": {respuesta: "C", materia: "Historia"}, 
    "28": {respuesta: "B", materia: "Historia"}, 
    "29": {respuesta: "D", materia: "Historia"},
    "30": {respuesta: "D", materia: "Historia"},
    "31": {respuesta: "D", materia: "Historia"},
    "32": {respuesta: "C", materia: "Historia"},
    "33": {respuesta: "C", materia: "Historia"},
    "34": {respuesta: "A", materia: "Historia"}, 
    "35": {respuesta: "A", materia: "Historia"},
    "36": {respuesta: "C", materia: "Formación Civica y Ética"},
    "37": {respuesta: "B", materia: "Formación Civica y Ética"}, 
    "38": {respuesta: "D", materia: "Formación Civica y Ética"},
    "39": {respuesta: "C", materia: "Formación Civica y Ética"}, 
    "40": {respuesta: "A", materia: "Formación Civica y Ética"},
    "41": {respuesta: "D", materia: "Formación Civica y Ética"}, 
    "42": {respuesta: "C", materia: "Formación Civica y Ética"}, 
    "43": {respuesta: "A", materia: "Formación Civica y Ética"}, 
    "44": {respuesta: "C", materia: "Formación Civica y Ética"}, 
    "45": {respuesta: "A", materia: "Formación Civica y Ética"},
    "46": {respuesta: "A", materia: "Formación Civica y Ética"}, 
    "47": {respuesta: "A", materia: "Formación Civica y Ética"}
};

const clavesExactas = {
    "0": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático"},
    "1": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático"},
    "2": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático"},
    "3": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático"},
    "4": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático"},
    "5": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático"},
    "6": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático"},
    "7": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático"},
    "8": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático"},
    "9": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático"},
    "10": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático"},
    "11": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático"},
    "12": {respuesta: "B", materia: "Matemáticas" },
    "13": {respuesta: "B", materia: "Matemáticas" },
    "14": {respuesta: "D", materia: "Matemáticas" },
    "15": {respuesta: "D", materia: "Matemáticas" },
    "16": {respuesta: "D", materia: "Matemáticas" },
    "17": {respuesta: "B", materia: "Matemáticas" },
    "18": {respuesta: "C", materia: "Matemáticas" },
    "19": {respuesta: "B", materia: "Matemáticas" },
    "20": {respuesta: "C", materia: "Matemáticas" },
    "21": {respuesta: "C", materia: "Matemáticas" },
    "22": {respuesta: "C", materia: "Matemáticas" },
    "23": {respuesta: "A", materia: "Matemáticas" },
    "24": {respuesta: "A", materia: "Fisíca" },
    "25": {respuesta: "A", materia: "Fisíca" },
    "26": {respuesta: "C", materia: "Fisíca" },
    "27": {respuesta: "B", materia: "Fisíca" },
    "28": {respuesta: "A", materia: "Fisíca" },
    "29": {respuesta: "C", materia: "Fisíca" },
    "30": {respuesta: "D", materia: "Fisíca" },
    "31": {respuesta: "D", materia: "Fisíca" },
    "32": {respuesta: "C", materia: "Fisíca" },
    "33": {respuesta: "D", materia: "Fisíca" },
    "34": {respuesta: "A", materia: "Fisíca" },
    "35": {respuesta: "D", materia: "Fisíca" },
    
   
};

const clavesExperimentales = {
    "0": {respuesta: "D", materia: "Química" },
    "1": {respuesta: "B", materia: "Química" },
    "2": {respuesta: "D", materia: "Química" },
    "3": {respuesta: "A", materia: "Química" },
    "4": {respuesta: "B", materia: "Química" },
    "5": {respuesta: "A", materia: "Química" },
    "6": {respuesta: "C", materia: "Química" },
    "7": {respuesta: "C", materia: "Química" },
    "8": {respuesta: "A", materia: "Química" },
    "9": {respuesta: "C", materia: "Química" },
    "10": {respuesta: "C", materia: "Química" },
    "11": {respuesta: "D", materia: "Química" },
    "12": {respuesta: "A", materia: "Biología" },
    "13": {respuesta: "B", materia: "Biología" },
    "14": {respuesta: "A", materia: "Biología" },
    "15": {respuesta: "C", materia: "Biología" },
    "16": {respuesta: "A", materia: "Biología" },
    "17": {respuesta: "B", materia: "Biología" },
    "18": {respuesta: "C", materia: "Biología" },
    "19": {respuesta: "B", materia: "Biología" },
    "20": {respuesta: "D", materia: "Biología" },
    "21": {respuesta: "B", materia: "Biología" },
    "22": {respuesta: "B", materia: "Biología" },
    "23": {respuesta: "C", materia: "Biología" },
    "24": {respuesta: "B", materia: "Geografía" },
    "25": {respuesta: "B", materia: "Geografía" },
    "26": {respuesta: "C", materia: "Geografía" },
    "27": {respuesta: "C", materia: "Geografía" },
    "28": {respuesta: "B", materia: "Geografía" },
    "29": {respuesta: "B", materia: "Geografía" },
    "30": {respuesta: "D", materia: "Geografía" },
    "31": {respuesta: "B", materia: "Geografía" },
    "32": {respuesta: "A", materia: "Geografía" },
    "33": {respuesta: "B", materia: "Geografía" },
    "34": {respuesta: "A", materia: "Geografía" },
    "35": {respuesta: "C", materia: "Geografía" },
};

// Exportamos las tres áreas para que el servidor pueda usarlas
module.exports = { 
    clavesSociales, 
    clavesExactas, 
    clavesExperimentales 
};