/**
 * ============================================================
 * ARCHIVO: claves_examen.js
 * UBICACIÓN: /backend/claves_examen.js (Al lado de server.js)
 * PROPÓSITO: Bóveda de respuestas correctas para todas las áreas.
 * ============================================================
 */

const clavesSociales = {
    "0": {respuesta: "D", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Comprensión Lectora"},
    "1": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Comprensión Lectora"},
    "2": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Comprensión Lectora"},
    "3": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Comprensión Lectora"},
    "4": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Comprensión Lectora"},
    "5": {respuesta: "A", materia: "Habilidad del Razonamiento Verbal", tema: "Semántica y Vocabulario", subtema: "Homónimos, Antónimos, Homófonos y Sinónimos"}, 
    "6": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal", tema: "Semántica y Vocabulario", subtema: "Homónimos, Antónimos, Homófonos y Sinónimos"},
    "7": {respuesta: "D", materia: "Habilidad del Razonamiento Verbal", tema: "Comprensión y Análisis de Textos", subtema: "Resumen"},
    "8": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal", tema: "Semántica y Vocabulario", subtema: "Homónimos, Antónimos, Homófonos y Sinónimos"},
    "9": {respuesta: "C", materia: "Habilidad del Razonamiento Verbal", tema: "Semántica y Vocabulario", subtema: "Campo semántico"},
    "10": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal", tema: "Tipos de Textos y sus Características", subtema: "Ensayo"},
    "11": {respuesta: "B", materia: "Habilidad del Razonamiento Verbal", tema: "Tipos de Textos y sus Características", subtema: "Mitos"},
    "12": {respuesta: "D", materia: "Español", tema: "Gramática y Estructura de la Oración", subtema: "Oraciones"},
    "13": {respuesta: "B", materia: "Español", tema: "Manejo de Información y Redacción", subtema: "Formato APA"},
    "14": {respuesta: "D", materia: "Español", tema: "Manejo de Información y Redacción", subtema: "Paráfrasis"},
    "15": {respuesta: "A", materia: "Español", tema: "Manejo de Información y Redacción", subtema: "Ejemplificación"},
    "16": {respuesta: "C", materia: "Español", tema: "Gramática y Estructura de la Oración",  subtema: "Oraciones"},
    "17": {respuesta: "A", materia: "Español", tema: "Semántica y Vocabulario", subtema: "Recursos semánticos"},
    "18": {respuesta: "B", materia: "Español", tema: "Tipos de Textos y sus Características", subtema: "Texto Publicitario"}, 
    "19": {respuesta: "C", materia: "Español", tema: "Tipos de Textos y sus Características", subtema: "Texto Publicitario"},
    "20": {respuesta: "C", materia: "Español", tema: "Gramática y Estructura de la Oración", subtema: "Tiempos Verbales"},
    "21": {respuesta: "A", materia: "Español", tema: "Tipos de Textos y sus Características", subtema: "Texto Argumentativo"},
    "22": {respuesta: "D", materia: "Español", tema: "Tipos de Textos y sus Características", subtema: "Noticia"},
    "23": {respuesta: "B", materia: "Español", tema: "Gramática y Estructura de la Oración", subtema: "Verbos Modales"}, 
    "24": {respuesta: "D", materia: "Historia", tema: "Historia Universal: Del Siglo XVI al XIX", subtema: "Tipos de Gobierno"}, 
    "25": {respuesta: "C", materia: "Historia", tema: "Historia Universal: Mundo Contemporáneo", subtema: "Segunda Guerra Mundial"},
    "26": {respuesta: "B", materia: "Historia", tema: "Historia Universal: Del Siglo XVI al XIX", subtema: "Humanismo"},
    "27": {respuesta: "C", materia: "Historia", tema: "Historia Universal: Mundo Contemporáneo", subtema: "Primer Guerra Mundial"}, 
    "28": {respuesta: "B", materia: "Historia", tema: "Historia de México: Colonial y Siglo XIX", subtema: "Consejo de Indias"}, 
    "29": {respuesta: "D", materia: "Historia", tema: "Historia de México: Colonial y Siglo XIX", subtema: "Virreinato"},
    "30": {respuesta: "D", materia: "Historia", tema: "Historia de México: Colonial y Siglo XIX", subtema: "Leyes de Reforma"},
    "31": {respuesta: "D", materia: "Historia", tema: "Historia de México: México Contemporáneo", subtema: "Primer Presidente Civil Posrevolucionario"},
    "32": {respuesta: "C", materia: "Historia", tema: "Historia de México: México Contemporáneo", subtema: "Revolución Mexicana"},
    "33": {respuesta: "C", materia: "Historia", tema: "Historia Universal: Mundo Contemporáneo", subtema: "Guerra del Golfo Pérsico"},
    "34": {respuesta: "A", materia: "Historia", tema: "Historia Universal: Mundo Contemporáneo", subtema: "Segunda Guerra Mundial en México"}, 
    "35": {respuesta: "A", materia: "Historia", tema: "Historia Universal: Del Siglo XVI al XIX", subtema: "Revolución Industrial"},
    "36": {respuesta: "C", materia: "Formación Civica y Ética", tema: "Desarrollo Personal y Cultura de Paz", subtema: "Recursos efectivos"},
    "37": {respuesta: "B", materia: "Formación Civica y Ética", tema: "Desarrollo Personal y Cultura de Paz", subtema: "M.gandhi (Líder social)"}, 
    "38": {respuesta: "D", materia: "Formación Civica y Ética", tema: "Estado, Constitución y Democracia", subtema: "Artículo 40 Constitucional"},
    "39": {respuesta: "C", materia: "Formación Civica y Ética", tema: "Formación Ética y Valores", subtema: "Diversidad"}, 
    "40": {respuesta: "A", materia: "Formación Civica y Ética", tema: "Estado, Constitución y Democracia", subtema: "Himno Nacional Mexicano"},
    "41": {respuesta: "D", materia: "Formación Civica y Ética", tema: "Estado, Constitución y Democracia", subtema: "Artículo 130 Constitucional"}, 
    "42": {respuesta: "C", materia: "Formación Civica y Ética", tema: "Formación Ética y Valores", subtema: "Valores Estéticos"}, 
    "43": {respuesta: "A", materia: "Formación Civica y Ética", tema: "Estado, Constitución y Democracia", subtema: "Normas Jurídicas"}, 
    "44": {respuesta: "C", materia: "Formación Civica y Ética", tema: "Estado, Constitución y Democracia", subtema: "Democracia"}, 
    "45": {respuesta: "A", materia: "Formación Civica y Ética", tema: "Formación Ética y Valores", subtema: "Valores"},
    "46": {respuesta: "A", materia: "Formación Civica y Ética", tema: "Desarrollo Personal y Cultura de Paz", subtema: "Necesidades del Ser Humano"}, 
    "47": {respuesta: "A", materia: "Formación Civica y Ética", tema: "Desarrollo Personal y Cultura de Paz", subtema: "Sustentabilidad para Desarrollo y Bienestar"}
};

const clavesExactas = {
    "0": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático", tema: "Razonamiento Aritmético", subtema: "Regla de Tres"},
    "1": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático", tema: "Sucesiones y Series", subtema: "Serie"},
    "2": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático", tema: "Imaginación Espacial y Visual", subtema: "Descomposición de Cuerpos Geométricos"},
    "3": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático", tema: "Imaginación Espacial y Visual", subtema: "Conteo de figuras"},
    "4": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático", tema: "Imaginación Espacial y Visual", subtema: "Formulas de Áreas de Cuerpos Geométricos"},
    "5": {respuesta: "D", materia: "Habilidad del Razonamiento Matemático", tema: "Imaginación Espacial y Visual", subtema: "Secuencia Geométrica"},
    "6": {respuesta: "A", materia: "Habilidad del Razonamiento Matemático", tema: "Imaginación Espacial y Visual", subtema: "Álgebra y Geometría Conceptos"},
    "7": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático", tema: "Sucesiones y Series", subtema: "Sucesión"},
    "8": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático", tema: "Sucesiones y Series", subtema: "Serie"},
    "9": {respuesta: "C", materia: "Habilidad del Razonamiento Matemático", tema: "Sucesiones y Series", subtema: "Sucesión"},
    "10": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático", tema: "Razonamiento Aritmético", subtema: "Fraccciones"},
    "11": {respuesta: "B", materia: "Habilidad del Razonamiento Matemático", tema: "Sucesiones y Series", subtema: "Serie"},
    "12": {respuesta: "B", materia: "Matemáticas", tema: "Probabilidad y Estadística", subtema: "Probabilidad"},
    "13": {respuesta: "B", materia: "Matemáticas", tema: "Álgebra", subtema: "Equivalencias Algebraicas"},
    "14": {respuesta: "D", materia: "Matemáticas", tema: "Geometría", subtema: "Tipos de triángulos" },
    "15": {respuesta: "D", materia: "Matemáticas", tema: "Aritmética (Proporcionalidad y Números)", subtema: "Constante de Proporcionalidad" },
    "16": {respuesta: "D", materia: "Matemáticas", tema: "Aritmética (Proporcionalidad y Números)", subtema: "Regla de Tres Inversa" },
    "17": {respuesta: "B", materia: "Matemáticas", tema: "Geometría", subtema: "Tipos de triángulos" },
    "18": {respuesta: "C", materia: "Matemáticas", tema: "Aritmética (Proporcionalidad y Números)", subtema: "Proporciones" },
    "19": {respuesta: "B", materia: "Matemáticas", tema: "Aritmética (Proporcionalidad y Números)", subtema: "Fracciones y Decimales" },
    "20": {respuesta: "C", materia: "Matemáticas", tema: "Geometría", subtema: "Cuerpos Geométricos y Fórmula del Volumen" },
    "21": {respuesta: "C", materia: "Matemáticas", tema: "Geometría", subtema: "Poliedros" },
    "22": {respuesta: "C", materia: "Matemáticas", tema: "Geometría", subtema: "Tipos de triángulos"},
    "23": {respuesta: "A", materia: "Matemáticas", tema: "Álgebra", subtema: "Trinomio Cuadrado Perfecto" },
    "24": {respuesta: "A", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Energía cinética" },
    "25": {respuesta: "A", materia: "Fisíca", tema: "Electromagnetismo", subtema: "Imán" },
    "26": {respuesta: "C", materia: "Fisíca", tema: "Óptica y Acústica (Ondas)", subtema:"Propiedades de la Luz" },
    "27": {respuesta: "B", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Caída Libre" },
    "28": {respuesta: "A", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Tipos de Movimiento" },
    "29": {respuesta: "C", materia: "Fisíca", tema: "Electromagnetismo", subtema: "Cargas Eléctricas" },
    "30": {respuesta: "D", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Tiro Parabólico" },
    "31": {respuesta: "D", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Leyes de Newton" },
    "32": {respuesta: "C", materia: "Fisíca", tema: "Termodinámica y Fluidos", subtema: "Temperaturas" },
    "33": {respuesta: "D", materia: "Fisíca", tema: "Mecánica (Cinemática y Dinámica)", subtema: "Tipos de Movimiento" },
    "34": {respuesta: "A", materia: "Fisíca", tema: "Termodinámica y Fluidos", subtema: "Unidad de Presión del Sistema Internacional" },
    "35": {respuesta: "D", materia: "Fisíca", tema: "Óptica y Acústica (Ondas)", subtema: "Características de la Onda" }
};

const clavesExperimentales = {
    "0": {respuesta: "D", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "Enlace Metálico" },
    "1": {respuesta: "B", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "El Átomo" },
    "2": {respuesta: "D", materia: "Química", tema: "Clasificación y Propiedades", subtema: "Mezcla heterogénea" },
    "3": {respuesta: "A", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "Molécula" },
    "4": {respuesta: "B", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "Enlace Iónico" },
    "5": {respuesta: "A", materia: "Química", tema: "Reacciones Químicas y Estequiometría", subtema: "Reacción química"},
    "6": {respuesta: "C", materia: "Química", tema: "Clasificación y Propiedades", subtema: "Propiedades Químicas y Físicas" },
    "7": {respuesta: "C", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "Neutrones" },
    "8": {respuesta: "A", materia: "Química", tema: "Estructura de la Materia y Enlaces", subtema: "Indicadores Atómicos" },
    "9": {respuesta: "C", materia: "Química", tema: "Reacciones Químicas y Estequiometría", subtema: "Unidad Mol"},
    "10": {respuesta: "C", materia: "Química", tema: "Clasificación y Propiedades", subtema: "Estados de Agregación" },
    "11": {respuesta: "D", materia: "Química", tema: "Reacciones Químicas y Estequiometría", subtema: "Agente REDOX"},
    "12": {respuesta: "A", materia: "Biología", tema: "Salud Reproductiva y Sexualidad", subtema: "Enfermedades de Transmisión Sexual" },
    "13": {respuesta: "B", materia: "Biología", tema: "Biodiversidad y Seres Vivos", subtema: "Reinos Biológicos" },
    "14": {respuesta: "A", materia: "Biología", tema: "Biología Celular y Genética", subtema: "ADN" },
    "15": {respuesta: "C", materia: "Biología", tema: "Salud Reproductiva y Sexualidad", subtema: "Órganos Reproductores" },
    "16": {respuesta: "A", materia: "Biología", tema: "Salud Reproductiva y Sexualidad", subtema: "Órganos Reproductores" },
    "17": {respuesta: "B", materia: "Biología", tema: "Biología Celular y Genética", subtema: "Mutación"},
    "18": {respuesta: "C", materia: "Biología", tema: "Biodiversidad y Seres Vivos", subtema: "Características de los Seres Vivos"},
    "19": {respuesta: "B", materia: "Biología", tema: "Biología Celular y Genética", subtema: "Estructuras Genéticas"},
    "20": {respuesta: "D", materia: "Biología", tema: "Biodiversidad y Seres Vivos", subtema: "Científicos y Aportaciones" },
    "21": {respuesta: "B", materia: "Biología", tema: "Biología Celular y Genética", subtema: "Célula Vegetal" },
    "22": {respuesta: "B", materia: "Biología", tema: "Biología Celular y Genética", subtema: "Respiración Celular" },
    "23": {respuesta: "C", materia: "Biología", tema: "Biología Celular y Genética", subtema: "Reproducción Celular"},
    "24": {respuesta: "B", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema: "El Planeta Tierra" },
    "25": {respuesta: "B", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema: "Cuerpos de Agua" },
    "26": {respuesta: "C", materia: "Geografía", tema: "Medio Ambiente y Sustentabilidad", subtema: "Contaminación" },
    "27": {respuesta: "C", materia: "Geografía", tema: "Geografía Humana y Población", subtema: "Migración y Derivados" },
    "28": {respuesta: "B", materia: "Geografía", tema: "Medio Ambiente y Sustentabilidad", subtema: "Diversidad en México"},
    "29": {respuesta: "B", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema : "Capas de la atmosfera"},
    "30": {respuesta: "D", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema: "Regiones Naturales"},
    "31": {respuesta: "B", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema: "Geosistemas" },
    "32": {respuesta: "A", materia: "Geografía", tema: "Medio Ambiente y Sustentabilidad", subtema: "Desarrollo Sustentable"},
    "33": {respuesta: "B", materia: "Geografía", tema: "Geografía Humana y Población", subtema: "Fronteras en México" },
    "34": {respuesta: "A", materia: "Geografía", tema: "Geografía Humana y Población", subtema: "Habitad y Poblaciones" },
    "35": {respuesta: "C", materia: "Geografía", tema: "Geografía Física y Geosistemas", subtema: "Rotación Terrestre" }
};

module.exports = { 
    clavesSociales, 
    clavesExactas, 
    clavesExperimentales 
};